### ISSUE TITLE
Q-

### ISSUE THREAD

**Issue by Frances-Zhang311** [M0dred/M0dred#1]
Q1-可提升空间具体指哪些方面

**Comment by M0dred** [comment]
> Q1-可提升空间具体指哪些方面

[Intelligence, Counter-intelligence and Security Support to Joint Operations (JDP 2-00)](https://assets.publishing.service.gov.uk/media/653a4b0780884d0013f71bb0/JDP_2_00_Ed_4_web.pdf)

[Psychology of Intelligence Analysis]
(https://www.cia.gov/resources/csi/static/Pyschology-of-Intelligence-Analysis.pdf)

[JP 2-0, Joint Intelligence]
(https://irp.fas.org/doddir/dod/jp2_0.pdf)
